In [2]:

import torch
import numpy as np

LISTS

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays

In [4]:
np1 = np.random.randn(3, 4)
np1

array([[ 0.2840852 , -0.51502949, -0.14724319,  0.12328261],
       [ 0.19270011, -0.75540951, -0.1223334 , -1.45924848],
       [ 0.72298271, -1.3547476 , -1.68664031, -0.14930161]])

In [ ]:
np1.dtype # see data type

dtype('float64')

Tenstors

In [ ]:
tensor_2d = torch.randn(3, 4)
tensor_2d # you can even see that it is called a tensor, so it is its own like, like an array or list

tensor([[-0.9960, -1.2781,  0.3702, -1.0307],
        [ 0.2995, -0.4391,  1.2423, -0.8822],
        [-1.3782,  0.0486, -0.5227, -0.6762]])

In [9]:
tensor_3d = torch.randn(2, 3, 4)
tensor_3d

tensor([[[ 1.5471, -0.4845,  1.7639, -0.1635],
         [-0.5254, -1.1331, -0.1057, -0.9952],
         [-0.6980, -1.7338,  0.0850,  1.4159]],

        [[-0.2354,  0.1199,  0.0152, -0.2794],
         [-0.0227,  0.7317,  0.8421,  1.8241],
         [ 0.5194,  1.8061, -0.0988, -1.5309]]])

In [10]:
## Create tensors from numpy arrays
my_tensor = torch.from_numpy(np1)
my_tensor

tensor([[ 0.2841, -0.5150, -0.1472,  0.1233],
        [ 0.1927, -0.7554, -0.1223, -1.4592],
        [ 0.7230, -1.3547, -1.6866, -0.1493]], dtype=torch.float64)